### ISSUE TITLE
[Errno 13] Permission denied: '/results_diff'

### ISSUE THREAD

**Issue by ontheway-arch** [buxiangzhiren/DDCap#15]
[Errno 13] Permission denied: '/results_diff'训练时出现这个错误，请问该如何解决？

**Comment by buxiangzhiren** [comment]
看起来像是在读取你生成的文件的时候，没有权限读取导致的。你可以给权限给 读取'/results_diff'的文件 或者 所在文件夹 试试。

**Comment by ontheway-arch** [comment]
请问--out_dir这个参数是什么含义呢？可以去掉吗，我的目录里好像找不到名为'/results_diff'的文件

**Comment by buxiangzhiren** [comment]
outdir是保存输出结果和模型的路径。我猜是你改了什么路径位置，你可以仔细检查一下看看你在哪里设置了'/results_diff'

**Comment by buxiangzhiren** [comment]
如果你是按照我原来的设置，'/results_diff'就是存放最后训练结果的文件夹。

**Comment by ontheway-arch** [comment]
我发现运行完之后，在项目上一级目录下确实多了个results_diff文件，但权限都开着

**Comment by buxiangzhiren** [comment]
是文件不是文件夹吗？

**Comment by ontheway-arch** [comment]
是文件夹

**Comment by buxiangzhiren** [comment]
你可以在生成'/results_diff'之后用sudo chmod 777 xxx给你整个项目权限试试。也可以改下outdir试试

**Comment by buxiangzhiren** [comment]
如果还不行，你可以把整个报错截图给我看

**Comment by ontheway-arch** [comment]
谢谢这个问题我已解决
