### ISSUE TITLE
运行程序问题

### ISSUE THREAD

**Issue by Leng-bingo** [buxiangzhiren/DDCap#2]
请问参数--data中的vit.pkl文件是从哪里获取呢

**Comment by Leng-bingo** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    非常感谢，麻烦了
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                805477481
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2022年11月25日 20:21
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [buxiangzhiren/DDCap] 运行程序问题 (Issue #2)
        
      
    
  
  

抱歉我当时忘记上传了，我们晚点会上传。上传完我会再发给您消息，



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by buxiangzhiren** [comment]
你看看能下载吗？https://drive.google.com/file/d/1CVsEQ5YRH3b6ZVRr7gY7ni7Ge1TgHvuM/view?usp=share_link

**Comment by Leng-bingo** [comment]
可以下载，非常感谢
