### ISSUE TITLE
Any formula for q_pred function ? 

### ISSUE THREAD

**Issue by linmou** [buxiangzhiren/DDCap#25]
Thanks for your excellent work of diffusion-based image-caption.

However, I am confused about the alpha schedular and the q_pred function.  I did not find any useful paragraph introducing this process in the paper. 

Which paper do you build this function on?  <Vector Quantized Diffusion Model for Text-to-Image Synthesis> , or others?

**Comment by buxiangzhiren** [comment]
We followed this paper (https://github.com/microsoft/VQ-Diffusion). Plus, I think the 13-th page of this paper could help you (https://arxiv.org/pdf/2102.05379.pdf).
